### PR TITLE
Focus-able div elements

### PR DESCRIPTION
**Pull request by phreed**
I have checked the behavior of the isis-ui-components and it appears to be unchanged.
My sample application: webgme-immortals uses the revised css for focusable main-menu elements.
Here is the style/immortals.css : 

```
ul.dropdown-navigator > li:not(.separator):hover > div.hierarchical-menu {
  transition-delay: 5s;
}

ul.dropdown-navigator > li:focus {
  visibility: visible;
  pointer-events: none;
}

ul.dropdown-navigator > li:focus > div.hierarchical-menu {
    pointer-events: none;
    visibility: visible;
    z-index: 3;
  }

ul.dropdown-navigator > li:focus > div.hierarchical-menu > ul.menu-contents {
      visibility: visible;
      opacity: 1;
      pointer-events: auto;
    }

ul.dropdown-navigator > li > div.hierarchical-menu > ul.menu-contents {
      visibility: hidden;
      opacity: 0;
      transition: visibility 0.5s;
    }
```

### CODE REVIEW

**Comment by lattmann** [comment]
@phreed I made the same change in this branch last week: https://github.com/webgme/webgme/tree/issue/843_dropdown_menu_on_click

You have to run npm install after you check out your branch. It pulled the new source code for me.

Did it pull the right version of the source code under src/client/bower_components?

I got the latest version when I ran npm install.

**Comment by phreed** [comment]
Yes, it pulled the right version of the source code.
I verified that it worked before making the pull request.
Do you want to do anything with the "immortals.css"?

**Comment by pmeijer** [comment]
@phreed is this working as expecting now?

**Comment by pmeijer** [comment]
Closed by #918
@phreed In the future, please squash the commits before making the PR. That way the master's history will be cleaner. In this case there already was a branch (#918) with the same changes so I will just merge that one.

**Pull request closed without merging**
