### PR TITLE
Fixes #566 css require paths should not depend on the document's path

### LINKED ISSUE #566: opening index.html directly screws styling
1. open localhost/index.html instead of localhost/
-> the styling of the page is odd (and there are some loading related error regarding some css files)

### PR DESCRIPTION
**Pull request by kecso**

### CODE REVIEW

**Comment by lattmann** [comment]
I do not think that we want these changes, does it work under this #522 use case? This pull request, is the opposite of the #522.

**Comment by pmeijer** [comment]
Tamas this fix works with /index.html and / if the config.client.appDir is the default. But not with a non-default.
On the other hand you're right about it not working without of this fix if /index.html is specified.
Suggested fix is the remove the index.html from document.location.pathname (if it exists).

**Comment by kecso** [comment]
thanks for the comments.
Couldn't we use the appdir config option instead of removing the index.html (it seems a bit of hacking, but temporarily can suffice)?
I'll check if it is possible and let you know if I have a solution for both use-cases

**Comment by kecso** [comment]
Patrik, I was able to make it work with some require rule changes (not the most beautiful, but works in all scenarios).
Please check it out!

**Comment by pmeijer** [comment]
How does it work?

**Pull request merged**
